name: 'procureiq'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
# staging -> STAGING schema, materialized as views (cheap, always fresh)
# intermediate -> STAGING schema, views
# marts -> ANALYTICS schema, tables (queried often, worth materializing)
models:
  procureiq:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics